runtime: go122
instance_class: F1
automatic_scaling:
  max_instances: 1

env_variables:
  GOLANGORG_CHECK_COUNTRY: true
  TOUR_ANALYTICS: |
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-39350154-1"></script>
    <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag("js", new Date());
    gtag("config", "UA-39350154-1");
    </script>

default_expiration: "1d"

# Keep these static file handlers in sync with local.go.
# They're here for improved latency across global regions.
handlers:
  - url: /.*
    script: auto
    secure: always
